FROM apache/airflow:2.7.3-python3.10
RUN pip install --no-cache-dir "apache-airflow[amazon]==${AIRFLOW_VERSION}" apache-airflow-providers-amazon>=8.16.0 boto3 airflow-provider-great-expectations airflow-clickhouse-plugin==1.1.0
